### PR TITLE
fix: helm action concurrency issues

### LINKED ISSUE #105: componentplan namespace is `u4a-system`, But the pod is deployed under the namespace of the repoisotory
componentplan namespace is `u4a-system`, But the pod is deployed under the namespace of the repoisotory.

image: 
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: cluster-compnent
  namespace: u4a-system
spec:
  approved: true
  name: cluster-component
  version: 0.1.0
  override:
    set:
    # according to https://kubebb.github.io/website/docs/core/get_started#kind%E5%BC%80%E5%8F%91%E9%9B%86%E7%BE%A4
    - ingress-nginx.deployedHost=kubebb-core-worker
  component:
    name: kubebb.cluster-component
    namespace: kubebb-system
```

ingress-nginx won't start because the pod can't be scheduled. the set parameter doesn't seem to be taking effect at the moment.

```yaml
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: kind-worker
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: cluster-component-ingress-nginx
  serviceAccountName: cluster-component-ingress-nginx
  terminationGracePeriodSeconds: 300
  tolerations:
```

pods

```shell
(base) ➜  cluster-component git:(main) ✗ kubectl get po -nkubebb-system
NAME                                                         READY   STATUS    RESTARTS   AGE
cert-manager-56585488fd-75hjn                                1/1     Running   0          19m
cert-manager-cainjector-797b96c765-759qx                     1/1     Running   0          19m
cert-manager-webhook-95fbbccd8-r96g7                         1/1     Running   0          19m
cluster-component-ingress-nginx-controller-bc5c5f9f5-l9hrx   0/1     Pending   0          19m
kubebb-7ddc7b946d-sw6nh                                      1/1     Running   0          23m
```

### LINKED ISSUE #126: remove duplicated reconcile resource
Lets see https://github.com/kubebb/core/blob/a450a095492b7a7ef845c234857c69184b5d76bc/controllers/componentplan_controller.go#L110

We return `Requeue:true` (Requeue tells the Controller to requeue the reconcile key.) and change CRD status. (Status change triggers reconcile logic)

So there will be 2 reconcile triggers here, which will **work properly, but are redundant** and will bring up a lot of extra error logs, like `the object has been modified; please apply your changes to the latest version and try again`, for example:
```
1.6896619680309799e+09	INFO	Try to add Finalizer for ComponentPlan	{"controller": "componentplan", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "ComponentPlan", "componentPlan": {"name":"nginx-15.0.2","namespace":"kubebb-system"}, "namespace": "kubebb-system", "name": "nginx-15.0.2", "reconcileID": "56ee3e87-97c3-41cd-a60c-b9365bd8d3cc"}
1.6896619680481248e+09	INFO	Adding Finalizer for ComponentPlan done	{"controller": "componentplan", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "ComponentPlan", "componentPlan": {"name":"nginx-15.0.2","namespace":"kubebb-system"}, "namespace": "kubebb-system", "name": "nginx-15.0.2", "reconcileID": "56ee3e87-97c3-41cd-a60c-b9365bd8d3cc"}
1.689661968048211e+09	INFO	Try to add Finalizer for ComponentPlan	{"controller": "componentplan", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "ComponentPlan", "componentPlan": {"name":"nginx-15.0.2","namespace":"kubebb-system"}, "namespace": "kubebb-system", "name": "nginx-15.0.2", "reconcileID": "e9114c34-7330-4a65-8c29-69453700b6be"}
1.6896619680535083e+09	ERROR	Failed to update ComponentPlan to add finalizer, will try again later	{"controller": "componentplan", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "ComponentPlan", "componentPlan": {"name":"nginx-15.0.2","namespace":"kubebb-system"}, "namespace": "kubebb-system", "name": "nginx-15.0.2", "reconcileID": "e9114c34-7330-4a65-8c29-69453700b6be", "error": "Operation cannot be fulfilled on componentplans.core.kubebb.k8s.com.cn \"nginx-15.0.2\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
1.6896619680539353e+09	ERROR	Reconciler error	{"controller": "componentplan", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "ComponentPlan", "componentPlan": {"name":"nginx-15.0.2","namespace":"kubebb-system"}, "namespace": "kubebb-system", "name": "nginx-15.0.2", "reconcileID": "e9114c34-7330-4a65-8c29-69453700b6be", "error": "Operation cannot be fulfilled on componentplans.core.kubebb.k8s.com.cn \"nginx-15.0.2\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
```

### PR DESCRIPTION
**Pull request by Abirdcfly**
- add syncMap and reduce unnecessary retry reconcile request (Fix #126) prevents multiple installations（Neither cpl.status nor helm releases are real-time, and there will be edge-case errors with these two judgments, but they can be used as a judgment condition after operator restarts) (xref #85)
- simplify componentplan's patchStatus function
- helm log update, fix helm installation ns (Fix #105)
- increase the concurrency of example-test from 5 to 10
- fix the problem in example-test and add the verification of helm revision after componentplan installation.

Fix https://github.com/kubebb/core/actions/runs/5585781404/jobs/10209054157#step:6:140 and https://github.com/kubebb/core/actions/runs/5595656655/jobs/10231821540

### CODE REVIEW

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /describe

**Comment by Abirdcfly** [comment]
need more detailed pr / commit message, look like bot is crashed...so sad.😭

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent  /describe

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /describe

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /review

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /improve

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /describe

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /review

**Comment by Abirdcfly** [comment]
@CodiumAI-Agent /improve

File: controllers/componentplan_controller.go [hunk 1]
```diff
@@ -161,23 +175,36 @@ func (r *ComponentPlanReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+			if r.inUninstallingMap(plan) {
+				logger.Info("another uninstall running, skip")
+				r.mu.Unlock()
+				return
+			}
+			r.addToUninstallingMap(plan)
+			r.mu.Unlock()
+			err = r.doFinalizerOperationsForPlan(ctx, logger, getter, plan)
+			r.removeFromUninstallingMap(plan)
+			r.removeFromPendingMap(plan)
```
Comment (bjwswang) [inline controllers/componentplan_controller.go:192]: why this place contains `removeFromPendingMap` ?

Comment (Abirdcfly) [reply controllers/componentplan_controller.go:192]: when uninstall, helm release will also unintall, So we should reset local cache for this release.

**Review by bjwswang — APPROVED** [review]

**Review by 0xff-dev — APPROVED** [review]
